name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. just clone the repo (no submodules)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. install our deps
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. run SA solver + validate via the contest checker in AIproject/
      - name: Run SA solver & validate
        run: |
          source .venv/bin/activate
          mkdir -p results
          for i in {1..5}; do
            python code/sa/solver_sa.py data/p1/instance.$i.in results/sa_$i.out
            python AIproject/lpcp-contest-2023/checker.py 1 $i < results/sa_$i.out
          done

      # 5. run CP-SAT solver + validate
      - name: Run CP-SAT solver & validate
        run: |
          source .venv/bin/activate
          mkdir -p results
          for i in {1..5}; do
            python code/cp_sat/solver_cp.py data/p1/instance.$i.in results/cp_$i.out
            python AIproject/lpcp-contest-2023/checker.py 1 $i < results/cp_$i.out
          done

      # 6. bundle SA outputs
      - name: Package SA solutions
        run: |
          source .venv/bin/activate
          mkdir -p artifacts
          zip -j artifacts/solutions.zip results/sa_*.out

      # 7. upload that ZIP
      - name: Upload SA ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: sa-solutions
          path: artifacts/solutions.zip
